server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: wechat-payment-demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment_demo
    username: root
    password: 123456
knife4j:
  enable: true
  openapi:
    title: "WeChat Payment"
    description: "WeChat Payment"
    email: xiaoymin@foxmail.com
    concat: 12345678
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0